stages:
  - fetch
  - test
  - build
  - deploy

fetch_code:
  image: python:3.7
  stage: fetch
  script:
    - git fetch --all
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME

run_tests:
  image: cambalab/python3-uno
  stage: test
  script:
    - pip install -r requirements/testing.txt -i https://pypi.python.org/simple
    - python manage.py test --settings=liberajus.settings.test

staging_deploy:
  image: cambalab/python3-uno
  stage: deploy
  script:
    - export APP_NAME=$([[ $CI_COMMIT_REF_NAME == "develop" ]] && echo "" || echo "-$CI_COMMIT_REF_NAME")
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "${DEPLOYMENT_STAGING_HOST}" >> ~/.ssh/known_hosts
    - git filter-branch -f -- --all
    - git push -f "${DEPLOYMENT_STAGING_USER}@${DEPLOYMENT_STAGING_HOST}:${DEPLOYMENT_STAGING_BASE_APP_NAME}${APP_NAME}" "${CI_COMMIT_REF_NAME}:master"
  only:
    refs:
      - develop
      - demo

build_image_and_upload_to_registry:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKERHUB_API_KEY\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination cambalab/liberajus:$CI_COMMIT_TAG
    - /kaniko/executor --context $CI_PROJECT_DIR/nginx --dockerfile $CI_PROJECT_DIR/nginx/Dockerfile --destination cambalab/liberajus-nginx:$CI_COMMIT_TAG
  only:
    - main
