version: "3.7"

services:
  main_db:
    container_name: "ia2_main_db"
    image: mariadb:10.4.11-bionic
    environment:
      MYSQL_USER: "${IA2_MAIN_DB_USER}"
      MYSQL_PASSWORD: "${IA2_MAIN_DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${IA2_MAIN_DB_ROOT_PASS}"
      MYSQL_DATABASE: "${IA2_MAIN_DB_NAME}"
    ports:
      - "${IA2_MAIN_DB_PORT}:3306"
    volumes:
      - main-db-volume:/var/lib/mysql/data
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

  data_db:
    container_name: "ia2_data_db"
    image: mariadb:10.4.11-bionic
    environment:
      MYSQL_USER: "${IA2_DB_DATA_USER}"
      MYSQL_PASSWORD: "${IA2_DB_DATA_PASS}"
      MYSQL_ROOT_PASSWORD: "${IA2_DB_DATA_ROOT_PASS}"
      MYSQL_DATABASE: "${IA2_DB_DATA_NAME}"
    ports:
      - "${IA2_DB_DATA_PORT}:3306"
    volumes:
      - data-db-volume:/var/lib/mysql/data
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

  adminer:
    container_name: "ia2_adminer"
    image: adminer
    ports:
      - "8080:8080"

  web:
    container_name: "ia2_django_app"
    restart: always
    image: ia2/django-app
    build:
      context: .
      dockerfile: "docker/development/Dockerfile"
      args:
        main_db_user: "${IA2_MAIN_DB_USER}"
        main_db_password: "${IA2_MAIN_DB_PASS}"
        main_db_root_password: "${IA2_MAIN_DB_ROOT_PASS}"
        main_db_name: "${IA2_MAIN_DB_NAME}"
        main_db_host: "main_db"
        main_db_port: "${IA2_MAIN_DB_PORT}"
        data_db_user: "${IA2_DB_DATA_USER}"
        data_db_password: "${IA2_DB_DATA_PASS}"
        data_db_root_password: "${IA2_DB_DATA_ROOT_PASS}"
        data_db_name: "${IA2_DB_DATA_NAME}"
        data_db_host: "data_db"
        data_db_port: "${IA2_DB_DATA_PORT}"
        model_file: ${IA2_MODEL_FILE}
        test_model_file: ${IA2_TEST_MODEL_FILE}
        secret_key: "${IA2_SECRET_KEY}"
        dropbox_token: "${PUBLICADOR_DROPBOX_TOKEN_APP}"
        disable_entities: "${IA2_DISABLED_ENTITIES}"
    entrypoint: "docker/development/django-entrypoint.sh"
    environment:
      OODOCUMENT_NEIGHBOR_CHARS_SCAN: "${OODOCUMENT_NEIGHBOR_CHARS_SCAN}"
      DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
      DEBUG: 1
      DOCKER_COMPOSE: 1
      IA2_ENABLE_OODOCUMENT_HEADER_EXTRACTION: "${IA2_ENABLE_OODOCUMENT_HEADER_EXTRACTION}"
      WAIT_HOSTS: main_db:3306, data_db:3306
      REDIS_HOST: redis
      BROKER_HOST: broker
      BROKER_USER: "${RABBITMQ_USERNAME}"
      BROKER_PASSWORD: "${RABBITMQ_PASSWORD}"
      BROKER_PORT: "${RABBITMQ_PORT}"
    ports:
      - "8000:8000"
    depends_on:
      - main_db
      - data_db
    volumes:
      - .:/app
    links:
      - main_db
      - data_db

  broker:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

volumes:
  main-db-volume:
  data-db-volume:
