# Generated by Django 2.2.5 on 2020-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_learningmodel_name_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
