# Generated by Django 2.2.5 on 2020-10-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0006_auto_20201014_1751"),
        ("entity", "0006_auto_20201013_2000"),
    ]

    operations = []
