# Generated by Django 2.2.5 on 2020-11-20 17:22

import apps.entity.validator
from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0009_auto_20201106_1553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="act",
            name="file",
            field=private_storage.fields.PrivateFileField(
                max_length=200,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="",
                validators=[apps.entity.validator.get_file_extension, apps.entity.validator.name_length],
            ),
        ),
    ]
