# Generated by Django 2.2.5 on 2020-11-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0010_auto_20201120_1422"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocurrencyentity",
            name="text",
            field=models.TextField(default="anotacion"),
        ),
    ]
