# Generated by Django 2.2.5 on 2021-01-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0013_ocurrencyentity_human_marked_ocurrency"),
    ]

    operations = [
        migrations.AddField(
            model_name="act",
            name="offset_header",
            field=models.IntegerField(default=0),
        ),
    ]
