# Generated by Django 2.2.5 on 2021-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0014_act_offset_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocurrencyentity",
            name="human_delete_ocurrency",
            field=models.BooleanField(default=False),
        ),
    ]
