# Generated by Django 2.2.5 on 2021-02-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0015_ocurrencyentity_human_delete_ocurrency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ocurrencyentity",
            old_name="human_delete_ocurrency",
            new_name="human_deleted_ocurrency",
        ),
    ]
