# Generated by Django 2.2.5 on 2021-03-09 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0016_auto_20210223_1201"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActStats",
            fields=[
                (
                    "act",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to="entity.Act"
                    ),
                ),
                ("load_time", models.DurationField(default=datetime.timedelta(0))),
                ("detection_time", models.DurationField(default=datetime.timedelta(0))),
                ("anonymization_time", models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
    ]
