# Generated by Django 2.2.5 on 2021-04-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0017_actstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='enable_multiple_selection',
            field=models.BooleanField(default=False),
        ),
    ]
