# Generated by Django 2.2.5 on 2021-04-05 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0017_actstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='actstats',
            name='extraction_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
