# Generated by Django 2.2.5 on 2021-05-21 18:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0018_entity_enable_multiple_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='actstats',
            name='begin_review_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='actstats',
            name='extraction_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='actstats',
            name='find_all_ocurrencies',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='actstats',
            name='review_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
