# Generated by Django 2.2.5 on 2021-04-29 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0018_entity_enable_multiple_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='actstats',
            name='extraction_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='actstats',
            name='find_all_ocurrencies',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
