# Generated by Django 2.2.5 on 2021-05-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0019_auto_20210505_1713'),
        ('entity', '0019_auto_20210505_1546'),
    ]

    operations = [
    ]
