# Generated by Django 2.2.5 on 2021-05-11 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0019_actstats_extraction_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="actstats",
            name="review_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
