# Generated by Django 2.2.5 on 2021-06-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0022_actstats_find_all_ocurrencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="act",
            name="hash_text",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
