# Generated by Django 2.2.5 on 2020-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lugar",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Hecho",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contexto_violencia", models.BooleanField(default=False)),
                ("contexto_violencia_de_genero", models.BooleanField(default=False)),
                ("fecha", models.DateField()),
                ("lugares", models.ManyToManyField(to="data.Lugar")),
            ],
        ),
    ]
