# Generated by Django 2.2.5 on 2020-11-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hecho",
            old_name="contexto_violencia",
            new_name="_contexto_violencia",
        ),
        migrations.RenameField(
            model_name="hecho",
            old_name="contexto_violencia_de_genero",
            new_name="_contexto_violencia_de_genero",
        ),
        migrations.AddField(
            model_name="historico",
            name="contexto_violencia",
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historico",
            name="contexto_violencia_de_genero",
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
    ]
