# Generated by Django 2.2.5 on 2020-11-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_auto_20201126_1512"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hecho",
            name="_fecha",
            field=models.DateField(blank=True),
        ),
    ]
