# Generated by Django 2.2.5 on 2020-11-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_auto_20201126_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hecho",
            name="_fecha",
            field=models.DateField(blank=True, null=True),
        ),
    ]
