# Generated by Django 2.2.5 on 2020-12-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20201222_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='edad_acusadx',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='edad_victima',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
